Epoch [1/50] Loss: 2.9856
Epoch [1/50] Loss: 2.8948
Epoch [1/50] Loss: 2.8644
Epoch [1/50] Loss: 2.6439
Epoch [1/50] Loss: 2.5342
Epoch [1/50] Loss: 2.4327
Epoch [1/50] Loss: 2.2821
Epoch [1/50] Loss: 2.1211
Epoch [1/50] Loss: 2.0459
Epoch [1/50] Loss: 1.8107
Epoch [1/50] Loss: 1.7426
Epoch [1/50] Loss: 1.7037
Epoch [1/50] Loss: 1.6673
Epoch [1/50] Loss: 1.3405
Epoch [1/50] Loss: 1.3401
Epoch [1/50] Loss: 1.4104
Epoch [1/50] Loss: 1.2514
Epoch [1/50] Loss: 1.6633
Epoch [1/50] Loss: 1.3636
Epoch [1/50] Loss: 1.6253
Epoch [1/50] Loss: 1.0009
Epoch [1/50] Loss: 1.3327
Epoch [1/50] Loss: 0.9858
Epoch [1/50] Loss: 1.4862
Epoch [1/50] Loss: 1.2756
Epoch [1/50] Loss: 1.3102
Epoch [1/50] Loss: 1.6404
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    train(args)
  File "train.py", line 87, in train
    outputs = model(images)
  File "/home/anouni/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anouni/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 73, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/anouni/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 83, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/anouni/.local/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
ValueError: Expected more than 1 value per channel when training, got input size [1L, 512L, 1L, 1L]
